services: 
  database:
    image: postgres
    container_name: webapp_postgres
    ports: [
      "8080:5432"
      ]
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=webapp_db
    